// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TennisFinal.Models;

namespace TennisFinal.Migrations
{
    [DbContext(typeof(MatchDBContext))]
    [Migration("20190214214541_RestrictionDate")]
    partial class RestrictionDate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TennisFinal.Models.Prenotation", b =>
                {
                    b.Property<int>("Id_Prenotazione")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Campo")
                        .IsRequired();

                    b.Property<DateTime>("Data");

                    b.Property<string>("Partita")
                        .IsRequired();

                    b.HasKey("Id_Prenotazione");

                    b.ToTable("Prenotations");
                });
#pragma warning restore 612, 618
        }
    }
}
